In [1]:
import numpy as np
from scipy.integrate import odeint

# Define the Lorenz '63 model equations
def lorenz_63(state, t, sigma, rho, beta):
    x, y, z = state
    return [
        sigma * (y - x),
        x * (rho - z) - y,
        x * y - beta * z
    ]

# Define the Jacobian matrix of the Lorenz '63 model
def jacobian_lorenz_63(state, sigma, rho, beta):
    x, y, z = state
    return np.array([
        [-sigma, sigma, 0],
        [rho - z, -1, -x],
        [y, x, -beta]
    ])

# Define the ODE for the linear propagator matrix M
def linear_propagator_ODE(M, t, state_traj, sigma, rho, beta):
    M = np.reshape(M, (3, 3))
    state = state_traj[int(t)]
    dMdt = np.dot(jacobian_lorenz_63(state, sigma, rho, beta), M)
    return dMdt.flatten()

# Time settings
dt = 0.01
T = 10.0
time = np.arange(0, T, dt)

# Lorenz '63 model parameters
sigma = 10.0
rho = 28.0
beta = 8/3

# Initial condition for the Lorenz '63 model
initial_state = [1.0, 1.0, 1.0]

# Integrate the Lorenz '63 model to get the trajectory
state_traj = odeint(lorenz_63, initial_state, time, args=(sigma, rho, beta))

# Initial condition for M(t=0) is the identity matrix
M0 = np.identity(3).flatten()

# Integrate the ODE for the linear propagator matrix M
M_traj = odeint(linear_propagator_ODE, M0, time, args=(state_traj, sigma, rho, beta))

# Extract M at the final time T
M_final = np.reshape(M_traj[-1], (3, 3))

print("The linear propagator matrix M at time T is:")
print(M_final)


The linear propagator matrix M at time T is:
[[ 9.48265415e+48  7.56071867e+48 -5.34782356e+47]
 [ 2.00948111e+49  1.60220136e+49 -1.13326398e+48]
 [ 5.49120037e+48  4.37824901e+48 -3.09680921e+47]]
